<div id="article">
	<div id="advertises">
		<?php 
		//article
		include_once('_advertises.inc');
		?>	
	</div>
	<div id="article-detail">
		<div id="article-content">	
			<div class="name">Quan an van Aiya</div>	
			<div class="title">Khuyen mai mung nam moi</div>	
			<div class="content">
				Còn gì tuyệt vời hơn nếu bạn khởi đầu một ngày mới bằng một tách cà phê hoặc những thức uống tươi mát, bổ dưỡng cho sức khỏe trong một không gian lãng mạn theo phong cách châu Âu? Vừa thưởng thức cà phê, vừa đọc báo ở một địa điểm yên tĩnh và lý tưởng quả là không còn gì bằng. Tọa lạc tại trung tâm quận 3, trên con đường Tú Xương, café Kaffeestube sẽ là một địa điểm vô cùng thú vị.
				Không chỉ quyến rũ bởi lối thiết kế độc đáo rất riêng, Cafe – Restaurant Kaffeestube còn làm say lòng thực khách bởi thực đơn vô cùng phong phú và hấp dẫn, hội tụ đến 3 phong cách ẩm thực khác nhau: Việt – Âu – Đức, phù hợp với mọi nhu cầu thưởng thức khác nhau của từng thực khách.
				Không gian quán được thiết kế theo phong cách Tây Âu xinh xắn, trang nhã và kèm theo là những bản nhạc cổ điển với giai điệu lãng mạn. Mỗi bàn đều được đặt một lọ hoa Salem xinh xắn, đáng yêu với ý nghĩa của muôn đời và mãi mãi. Trong thánh kinh đã từng nói rằng: “Hãy gửi một bó hoa có xen hoa Salem để người nhận biết rằng bạn nhớ họ”. Có lẽ, tương tự với ý nghĩa này, Kaffeestube cũng hy vọng sau một lần đến đây dùng cà phê, quý khách sẽ mãi mãi nhớ tới một chốn bình yên và ấm áp!
				Vào buổi tối Kafffeestube được trang trí những chiếc nến nho nhỏ, tạo nên sự ấm cúng cho quán. Kaffeestube có nghĩa là Coffee Shop, và tại đây bạn sẽ có dịp thưởng thức những thức uống với công thức được pha chế theo phong cách phương Tây.
				Ngoài cà phê, Kaffeestube còn phục vụ các thức uống sinh tố, cocktail,... nguyên liệu được nhập từ Ý cùng với các món ăn Âu - Việt và đặc biệt nhất là phong cách ẩm thực Đức chính hiệu. Bò Beefsteak Kaffeestube được chế biến theo công thức rất riêng mang hương vị của Lá Hương Thảo cùng rượu Bordeaux Red..ăn kèm với nước Sốt, Salad Âu cùng Khoai tây nướng chắn chắn sẽ làm hài lòng những thực khách khó tính nhất.
				Hãy đến với Kaffeestube để được thư giãn trong không gian ấm cúng, lắng nghe những tình khúc cổ điển lãng mạn và thưởng thức những món ăn thơm ngon, hấp dẫn bạn nhé!
			</div>			
		</div>		
		<?php 
		//article
		include_once('_comment_editor.inc');
		?>		
	</div>
	<div id="company-info">	
		<div id="company_address">
			<div class="name">An Vat Aiya</div>
			<div class="address">12 Bui Thi Xuan</div>
			<div class="mobile">(+084) 8 4332 332</div>
			<div class="website">aiya.com.vn</div>
		</div>
		<div id="company_map">
			<img class="map-address" src="images/map.jpg" />
		</div>
		<div id="company_partner">
			<img class="partner" src="images/partner.jpg" />
			<img class="partner" src="images/partner.jpg" />
			<img class="partner" src="images/partner.jpg" />
		</div>
	</div>
</div>