<div id="left-sider">
	<ul>
		Ăn uống- Giải trí
		<li>
			<a href="article_list">	Cafe/Kem/Bánh</a>
		</li>
		<li>
			<a href="article_list">	Quán ăn</a>
		</li>
		<li>
			<a href="article_list">	Bar/Pub</a>
		</li>
		<li>
			<a href="article_list">	Karaoke</a>
		</li>
		<li>
			<a href="article_list">	Phim/Nhạc/Kịch</a>
		</li>
		<li>
			<a href="article_list">	Nhà hàng</a>
		</li>
	</ul>
	
</div>