<?php
/*
 * This file was automatically generated By Code Smith 
 * Modifications will be overwritten when code smith is run
 *
 * PLEASE DO NOT MAKE MODIFICATIONS TO THIS FILE
 * Date Created 5/6/2012
 *
 */

/// <summary>
/// Implementations of slarticles represent a Article
///
/// </summary>

/* TODO: Add code here */
require('config/globalconfig.php');


?>


<?php
include_once('include/_header.inc');
?>
<script type="text/javascript" src="<?php echo $_objSystem->locateJs('user_article.js');?>"></script>
<div id="post-page" class="span10">
	<form method="POST" class="form-horizontal">
		<!--Begin Form Input -->
		<input type="hidden" id="adddocmode" name="adddocmode" value="1<?php //echo $intMode;?>" />
		<input type="hidden" id="txtPage" name="txtPage" value="<?php echo $_pgR["p"]?$intPage:1;?>" />
		<input type="hidden" id="txtID" name="txtID" value="" />
		<div class="table-post">
			<div class="control-group">
				<div class="controls">
					<h1 class="m-wrap title">Đăng tin khuyến mãi</h1>
				</div>
			</div>
			<div class="control-group margin-auto">
				<div class="controls">
					<label class="m-wrap">(*) là thông tin bắt buộc</label>
					<label class="m-wrap">KM: Khuyến mãi</label>
				</div>
			</div>
			<div class="control-group zone">
				<div class="controls">
					<h2 class="m-wrap zone-title">Thông tin đơn vị kinh doanh</h2>
				</div>
			</div>
			<div class="control-group">
				<label class="control-label">Tên đơn vị *</label>
				<div class="controls">
					<input type="text" name="txtCompanyName" id="txtCompanyName" class="text m-wrap span6" maxlength="255" />
				</div>
			</div>
			<div class="control-group">
				<label class="control-label">Địa chỉ *</label>
				<div class="controls">
					<input type="text" name="txtCompanyAddress" id="txtCompanyAddress" class="text m-wrap span6" maxlength="255" />
				</div>
			</div>
			<div class="control-group">
				<label class="control-label">Web/Facebook</label>
				<div class="controls">
					<input type="text" name="txtCompanySite" id="txtCompanySite" class="text m-wrap" maxlength="255" />
					<label class="m-wrap inline">Điện thoại *</label>
					<input type="text" name="txtCompanyPhone" id="txtCompanyPhone" class="text m-wrap span3" placeholder="Vd: 0123456789, 0123-456-789,..." maxlength="50" />
				</div>
			</div>
			<div class="control-group zone">
				<div class="controls">
					<h2 class="m-wrap zone-title">Thông tin khuyễn mãi</h2>
				</div>
			</div>
			<div class="control-group">
				<label class="control-label">Lĩnh vực *</label>
				<div class="controls">	
					<select class="span6 chosen" name="cmArea" id="cmArea" data-placeholder="Chọn lĩnh vực" multiple="multiple" tabindex="1">
						<option value="1" >Ăn uống/ Giải trí</option>
						<option value="2">Thời trang/ Làm đẹp</option>
					</select>
					<div class="help-inline message"></div>
				</div>
			</div>	
			<div class="control-group">	
				<label class="control-label">Chuyên Mục *</label>
				<div class="controls">	
					<select class="span6 chosen" name="cmCategory" id="cmCategory" data-placeholder="Chọn chuyên mục" multiple="multiple" tabindex="1">
						<option value="1" >Nhà hàng</option>
						<option value="2">Ăn vặt</option>
					</select>
					<div class="help-inline message"></div>					
				</div>
			</div>
			<div class="control-group">
				<label class="control-label">Loại khuyến mãi *</label>
				<div class="controls">
					<input type="text" name="txtAdTypeValue" id="txtAdTypeValue" class="text ad-value" placeholder="Mua 1 tặng 1" maxlength="15" />
					<div class="help-inline message"></div>			
				</div>
			</div>
			<div class="control-group">
				<label class="control-label">Từ *</label>
				<div class="controls">
					<div class="input-append date date-picker text" data-date="" readonly="readonly"  data-date-format="dd/mm/yyyy"  data-date-viewmode="days">
						<input name="txtStartDate" id="txtStartDate" class="m-wrap m-ctrl-medium date-picker "size="16" type="text" value="" placeholder="dd/mm/yyyy" />
							<span class="add-on"><i class="icon-calendar"></i></span>
					</div>
					<label class="m-wrap inline">Đến * </label>
					<div class="input-append date date-picker text " data-date=""  data-date-format="dd/mm/yyyy"  data-date-viewmode="days">
						<input name="txtEndDate" id="txtEndDate" class="m-wrap m-ctrl-medium date-picker" size="16" type="text" value="" placeholder="dd/mm/yyyy" />
							<span class="add-on"><i class="icon-calendar"></i></span>
					</div>
					<div class="help-inline message"></div>			
				</div>
			</div>
			<div class="control-group">
				<label class="control-label">Happy days</label>
				<div class="controls">
					<select class="span3 chosen" name="cmHappyDays" id="cmHappyDays" data-placeholder="Chọn ngày trong tuần" multiple="multiple" tabindex="1">
						<option value="Monday">Monday</option>
						<option value="Tuesday">Tuesday</option>
						<option value="Wednesday">Wednesday</option>
						<option value="Thursday">Thursday</option>
						<option value="Friday">Friday</option>
						<option value="Saturday">Saturday</option>
						<option value="Sunday">Sunday</option>
					</select>
				</div>
			</div>
				<div class="control-group">
				<label class="control-label">Happy hours</label>
				<div class="controls">
					<div class="input-append bootstrap-timepicker-component">
						<input name="txtHappyFrom" id="txtHappyFrom" class="m-wrap m-ctrl-small timepicker-24" type="text" />
						<span class="add-on"><i class="icon-time"></i></span>
					</div>
					<label class="m-wrap inline">Đến  </label>
					<div class="input-append bootstrap-timepicker-component">
						<input name="txtHappyTo" id="txtHappyTo"  class="m-wrap m-ctrl-small timepicker-24" type="text" />
						<span class="add-on"><i class="icon-time"></i></span>
					</div>
					<div class="help-inline message"></div>
				</div>
			</div>
			<div class="control-group">
				<label class="control-label">Tên chương trình KM *</label>
				<div class="controls">
					<input type="text" name="txtName" id="txtName" class="text span6 maxlength="255"  />
				</div>
			</div>
			<div class="control-group">
				<label class="control-label">Hình minh họa</label>
				<div class="controls">
					<input type="text" name="txtImage" id="txtImage" class="text span6 maxlength="255"  placeholder="vd: http://i134.photobucket.com/albums/q99/45748_0_square_1a.jpg"  />
				</div>
			</div>
			<div class="control-group address-article">
				<label class="control-label">Địa điểm *</label>
				<div class="controls">
					<input type="text" name="txtAddressArticle" id="txtAddressArticle" class="text m-wrap  span3" maxlength="255" placeholder="vd: 1A Trần Hưng Đạo" />
					
					<select id="optCity" name="optCity" class="chosen span2 m-wrap " single="single" data-placeholder="Chọn TP/Tỉnh" tabindex="1">
						<option value="HCM">HCM</option>
						<option value="HCM">HN</option>
					</select>
					<select id="optDistrict" name="optDistrict"  class="chosen span2 m-wrap " data-placeholder="Chọn Quận/Huyện" tabindex="1">
						<option value="Quận 1">Quận 1</option>
						<option value="Quận 2">Quận 2</option>
						<option value="Quận 3">Quận 3</option>
					</select>	
					<a href="javascript:void(0);" class="btn btn-mini btn-add" onclick="article.addLocation(this)"/><i class="icon-plus"></i> Thêm</a>
					<a href="javascript:void(0);" class="btn btn-mini btn-update no-display" onclick="article.updateLocation(this)"/><i class="icon-ok"></i> Cập nhật</a>
					<a href="javascript:void(0);" class="btn  btn-mini btn-cancel no-display" onclick="article.cancelLocation(this)"/></i> Hủy bỏ</a>
				</div>	
			</div>
			<div class="control-group">
				<label class="control-label">Nội dung *</label>
				<div class="controls">
					<textarea class="span6 ckeditor m-wrap" name="txtContent" id="txtContent" rows="6"></textarea>
					<div class="help-inline message"></div>					
				</div>
			</div>
			<div class="control-group">
				<label class="control-label">Tags </label>
				<div class="controls">
					<textarea id='txtTags' name='txtTags' class="m-wrap span6" rows="2"></textarea>
				</div>
			</div>
			<div class="control-group">
				<div class="controls">
						<label class="checkbox">
						<input type="checkbox" value="" /> Tôi đã đọc và đồng ý với <a href="#" class="link">điều khoản đăng tin</a>  của hệ thống timkm.com
					</label>
				</div>
			</div>
			<div class="control-group">				
				<div class="controls">
					<input type="button" name="btnOK" id="btnOK" class="btn" value="Đăng tin"/>
					<input type="reset" name="btnReset" id="btnReset" class="btn gray" value="Nhập lại"/>
				</div>
			</div>
		</div>
	</form>
</div>
<!--End Form Input -->
<?php 
//footer
include_once('include/_footer.inc');
?>
<script language="javascript" type="text/javascript">
    $(document).ready(function () {
			
			core.util.getObjectByID("btnOK").click(function(){
				 article.postArticle();			
			});
			
			/*
			core.util.getObjectByID("form-register").submit(function () {
               user.register();				
				return false;				
            });
			*/
			
    });
</script>